url: "/"
destination: build-output

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: null

sass:
  style: compressed

plugins:

exclude:
  - node_modules
